version: '3'
services:
  wireguard-qr:
    container_name: wireguard-qr
    image: wireguard-qr:0.0.2
    build: .
    restart: always
    user: "1000:1000"
    ports:
      - "5182:5182"
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/wireguard-qr/data